### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by metya** [flyingpie/windows-terminal-quake#20] opened 2020-09-08 16:21 UTC
The application does not work. 

The expected behavior:
Run the app, the app is working and ctrl+\` drops the terminal and process `windows-terminal-quake.exe` is in the processes.

But after a click on the app, only the terminal is opening and the process `windows-terminal-quake.exe` appears only in second in processes, and then it is disappearing.

I tried 0.5, 0.6 and 0.7 versions.

**Comment by webbertakken** [comment] 2020-09-08 16:56
Possible duplicate of: https://github.com/flyingpie/windows-terminal-quake/issues/13

Can you see if the linked pr works for you?

**Comment by flyingpie** [comment] 2020-09-08 21:50
@metya Should this problem have the same cause as the one @webbertakken is describing, there is a preview with a fix here:

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.8

Please let me know if that works for you :)

**Comment by metya** [comment] 2020-09-15 21:52
Sorry, for the late answer!

Yes, apparently it was this bug. Then open the app again when terminal is already working it fixes the problem. 

Now I download the new version 0.8. 
And when I'm trying just open it without administrative permission, there is a windows notification about that some error and nothing happens, only the normal terminal opens. But if I start it with administrative permission it starts normally.

![image](https://user-images.githubusercontent.com/968934/93268716-59beb380-f7b6-11ea-9d39-38672fa81825.png)

Sorry for the Russian. It says `the sequence contains no elements` or something like that. I don't know what it was originally, before localization.

**Comment by metya** [comment] 2020-09-15 22:33
Also, I notice that now terminal disappears without focus. And you need to cntl+` again every time. I think earlier there wasn't that behavior.

**Comment by Spencer-Dawson** [comment] 2020-09-17 20:37
I downloaded 0.8 today and see a "the sequence contains no elements" on launch. Terminal seems to launch fine, but It seems this utility crashes after it launches the terminal. I don't see any other error messages and get the same results whether or not I use administrative mode. I only started using 0.8 because the earlier version of this utility I was using stopped working(not sure which version offhand tbh). I am inclined to think that Microsoft changed something. I have Windows Terminal
'Version: 1.2.2381.0' and Windows 10 pro 'Version 10.0.19041 Build 19041'

**Comment by webbertakken** [comment] 2020-09-17 22:07
I'm now having this same error also. 

```
the sequence contains no elements
```

I can confirm that the same version worked before. I updated windows in between, but not the terminal.

Windows 10 Pro - version 1909 build 18363.1016

**Comment by metya** [comment] 2020-09-18 11:16
Version 0.7 works well, but you need to launch it twice. Minor problem to me, but without errors, though 😄

**Comment by webbertakken** [comment] 2020-09-22 16:27
Possibly related

> 1.3 ONLY: We've disabled the creation of a new process environment block due to a regression in Windows PowerShell
(x86); see #7418 for further details

source: [microsoft/terminal/releases/v1.3.2651.0](https://github.com/microsoft/terminal/releases/tag/v1.3.2651.0)

**Comment by webbertakken** [comment] 2020-09-22 16:43
Fixed in https://github.com/flyingpie/windows-terminal-quake/pull/25 for me. Seems like the program is simply too eager.

Tested with latest version of Terminal: `1.3.2651.0`

**Comment by metya** [comment] 2020-09-23 10:04
Well, waiting for the merge and new build.

**Comment by flyingpie** [comment] 2020-09-23 17:28
@webbertakken Thank you for looking into this bug :)

@metya Just made a pre release available here: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.9

Currently running this version myself, and @webbertakken I'm gonna take a closer look at the code change and the underlying problem soon.

**Comment by webbertakken** [comment] 2020-09-24 18:44
@metya could you have a look if this version works for you too?

**Comment by metya** [comment] 2020-09-25 16:56
sorry for the long answer. 
yes, it totally works for me.

seems now version 0.9 already fine

**Comment by flyingpie** [comment] 2020-09-28 00:07
@metya Thank you for the confirmation!

@webbertakken I'd like to change the sleep to a retry-construct, since now there's a chance the process isn't ready yet. With a retry such as the one I used for window opacity here: https://github.com/flyingpie/windows-terminal-quake/blob/master/windows-terminal-quake/Native/TransparentWindow.cs, we're no longer dependent on the process being ready after X milliseconds, and we don't have to wait at all if it works on the first try.

What are you thoughts?

**Comment by webbertakken** [comment] 2020-09-28 09:00
@flyingpie I guess that could work.

Could you please merge the current working version before you do and create 0.9 release?

That way we could work incrementally and check if something breaks every step of the way.

**Comment by metya** [comment] 2020-09-28 12:39
Hm.
After rebooting my computer behaviour of the app became as erlier sometimes.
I mean, sometimes when I click the app it launch terminal only, but sometime it works as normal, launch the terminal and the quake mode. Maybe time of sleep not enough or something like that.

**Comment by metya** [comment] 2020-09-29 02:12
And I have another question. When the terminal out of focus it disappears from the screen and I have to push ctrl + ` to get the terminal back. It is normal behavior or not?

**Comment by flyingpie** [comment] 2020-09-29 21:56
@webbertakken I'd rather make the code a little more robust before actually pushing out a "stable" release, if you don't mind :)

@metya: This is a later added feature "HideOnFocusLost": https://github.com/flyingpie/windows-terminal-quake/#hide-on-focus-lost.

You can turn it off, but I'd figure that it's perhaps the sensible default.

**Comment by flyingpie** [comment] 2020-10-05 23:45
@metya @webbertakken I've tweaked the code as provided by @webbertakken a bit and uploaded a new release. It's basically the same but a little more forgiving regarding the time of sleep.

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.9

**Comment by flyingpie** [comment] 2020-10-06 01:50
![](https://1.bp.blogspot.com/-YKHhejLOZ4s/UM8cceYyFTI/AAAAAAAAL0E/qldF5Y9XaSI/s1600/goodnewseveryone.jpg)

It seems that finally I can join the club of people with weird process issues. Perhaps updates to either Windows or Windows Terminal.

Anyway, I've been messing around some more and updated the v0.9 release, and I haven't encountered any problems so far. Note that I had all sorts of issues like the process not being picked up at all by windows-quake-terminal, or not being able to toggle anything.

Link for the lazy:

**Comment by webbertakken** [comment] 2020-10-06 10:52
I'll have a look soon.

**Comment by metya** [comment] 2020-10-06 14:48
thank you for update!

I tried a new release and at first look, it just works fine :)

But in release's zip name you named it with v0.8. Just noted :)

**Comment by flyingpie** [comment] 2020-10-06 22:41
@webbertakken Thank you, also, the work is still mostly yours, so I'd like to route the PR through you for proper attribution.

@metya F*CK, thanks for the heads-up :)

Let me know when your PC explodes. Send me a message through your microwave.

**Comment by flyingpie** [comment] 2020-10-08 00:54
Closing this issue for now, if anyone encounters the problem again, feel free to ~~smash the subscribe and~~  leave a comment.

**Closed by flyingpie** 2020-10-08 00:54 UTC
Labels: investigating
